### ISSUE TITLE
Add logic/methods for get the data from text field and insert it into the oracle database through prepared statement.

### ISSUE THREAD

**Issue by Ashutoshonly** [Ashutoshonly/Java-swing-project#1]
Write your solution [<b>here</b>](https://github.com/Ashutoshonly/Java-swing-project/tree/main/JavaApplication1/JavaApplication1/src/javaapplication1) in registration.java

**Comment by Harsh-bartariya** [comment]
I want to work on this issue kindly assign me this one also.

**Comment by Ashutoshonly** [comment]
Sure...add your code till 11 oct
