### ISSUE TITLE
Write the code for get the data through swing buttons and write the methods/logic for calculator[Division, Multiplication, Addition and Subtraction]

### ISSUE THREAD

**Issue by Ashutoshonly** [Ashutoshonly/Java-swing-project#2]
Write your solution [<b>here</b>](https://github.com/Ashutoshonly/Java-swing-project/tree/main/JavaApplication1/JavaApplication1/src/javaapplication1) in Calcu.java

**Comment by Harsh-bartariya** [comment]
I want to work on this issue kindly assign me.

**Comment by Ashutoshonly** [comment]
Okey sure...submit your solution till 11 oct
